## **Import Libraries**

In [2]:
import pandas as pd

## **Read the dataset from csv file**

In [7]:
df = pd.read_csv(r"C:\Users\tania\OneDrive\Documents\Data Projects\Python\Demographic Data Analyser\adult.data.csv")
df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

## **Question 1: Count people by race**

In [12]:
race_count = df["race"].value_counts()
race_count

race
White                 27816
Black                  3124
Asian-Pac-Islander     1039
Amer-Indian-Eskimo      311
Other                   271
Name: count, dtype: int64

## **Question 2: Average age of men**

In [17]:
average_age_men = round(df[df["sex"] == "Male"]["age"].mean(), 1) 
average_age_men

39.4

## **Question 3: Percentage with Bachelor’s degree**

In [20]:
percentage_bachelors = round(
    (df[df["education"] == "Bachelors"].shape[0] / df.shape[0]) * 100, 1
)
percentage_bachelors

16.4

## **Questions 4 and 5: Advanced education vs not advanced education**

#### **Defining Advanced Education**

In [27]:
higher_education = df["education"].isin(["Bachelors", "Masters", "Doctorate"])
lower_education = ~higher_education

#### **Finding rich people in both groups**

In [36]:
higher_education_rich = df[higher_education & (df["salary"] == ">50K")]

lower_education_rich = df[lower_education & (df["salary"] == ">50K")]

#### **Calculating percentages**

In [41]:
higher_education_rich = round(
    (higher_education_rich.shape[0] / df[higher_education].shape[0]) * 100, 1
)

lower_education_rich = round(
    (lower_education_rich.shape[0] / df[lower_education].shape[0]) * 100, 1
)

## **Question 6: Minimum hours worked per week**

In [44]:
min_work_hours = df["hours-per-week"].min()
min_work_hours

1

## **Question 7: Percentage of rich people among minimum-hour workers**

In [49]:
num_min_workers = df[df["hours-per-week"] == min_work_hours] #filtering people who work the minimum hours
rich_min_workers = num_min_workers[num_min_workers["salary"] == ">50K"] #from that group, filter those who earn >50K
rich_min_workers

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
189,58,State-gov,109567,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,1,United-States,>50K
20072,65,?,76043,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,0,1,United-States,>50K

In [53]:
rich_percentage = round(
    (rich_min_workers.shape[0] / num_min_workers.shape[0]) * 100, 1
)
rich_percentage

10.0

## **Question 8: Country with highest percentage of people earning >50K**

In [58]:
country_count = df["native-country"].value_counts() #count total people in each country

In [64]:
country_rich_count = df[df["salary"] == ">50K"]["native-country"].value_counts() #filter people earning more than 50k adn filter by country

In [66]:
country_rich_percentage = (country_rich_count / country_count) * 100 #Calculate rich percentage per country

In [70]:
#finding the highest earning country
highest_earning_country = country_rich_percentage.idxmax() 
highest_earning_country_percentage = round(country_rich_percentage.max(), 1) 
highest_earning_country

'Iran'

## **Question 9: Most popular occupation for rich people in India**

In [76]:
top_IN_occupation = (
    df[(df["native-country"] == "India") & (df["salary"] == ">50K")]["occupation"]
    .value_counts()
    .idxmax()
)
top_IN_occupation

'Prof-specialty'